name: matrix_dart_sdk_isar_db
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  matrix:
    git: 
      url: https://github.com/Airyzz/matrix-dart-sdk.git
      ref: krille/background-client
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.15.7
  file: ">=6.1.1 <8.0.0"
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9


flutter:
